# Data Science HW2 Data Wrangling
## Ushna Batool ub07100

In [2]:
import pandas as pd

In [3]:
Data = pd.read_csv('580SurveyCleanup.csv')

In [ ]:
Data

In [ ]:
Data.head(1)  #displays only 5 rows by default

In [5]:
Data.duplicated() #false means no duplicates
data1 = Data.iloc[:,1:12]

# Header

In [ ]:
data1.columns = data1.iloc[0] # replaces 0th index names as header
data1 = data1[1:] # excluding 0th row using slicing
data1.head()

#Q1

In [ ]:
data2 = Data.iloc[:,[12,13]]
data2.head() #getting Q1
data2.columns = data2.iloc[0]
data2 = data2[1:] #replacing 0th index as header
data2.head()

##Replacing one value with its column name

In [ ]:
data3 = data2.loc[:, "2.0":"4.0"].replace(1, pd.Series(data2.columns, data2.columns)).fillna('') #replacing 1s with respctive column names and
data3.head()

##Concatenating Q1 into Final column

In [ ]:
data4 = pd.DataFrame(data3.iloc[:,0].astype(str) + data3.iloc[:,1].astype(str)) # all rows of 1st and 2nd column are concatenated and converted in str to make sure they are handled properly
data4.columns = ['Which Section']
data4.head()

In [ ]:
data5 = pd.concat([data1,data4],axis=1) # creating a new dataframe by concateneing two data frames into one
data5.head()

#Q2

In [ ]:
data6 = Data.iloc[:,[14,15,16,17]] # all Q2 : means all rows of these mentioned columns
data6.columns = data6.iloc[0] #replacing 0th row as header
data6 = data6[1:] #excluding 0th row
data6.head() # by default shows first 5

##Replacing 1s with its column names

In [ ]:
data7 = data6.loc[:, :].replace('1', pd.Series(data6.columns, data6.columns)).fillna('') #replacing 1s with its value and filling NaN with " "
data7.head()

##Concatenation of Q2 with final column

In [ ]:
data8 = pd.DataFrame(data7.iloc[:,0] + data7.iloc[:,1] + data7.iloc[:,2] + data7.iloc[:,3])
data8.columns = ['Gender']
data8.head()

In [ ]:
data5 = pd.concat([data5,data8],axis=1)
data5.head()

## Concatenation of Q3-Q7

In [ ]:
data2 = Data.iloc[:,[18,19,20,21,22]] # all rows of specific columns are gathered using concatenation
data2.columns = data2.iloc[0].astype(str) # replacing header with 1st row
data2 = data2[1:]
data2.head()

## concatenating it in the data we have sorted before

In [ ]:
data5 = pd.concat([data5,data2],axis=1) # axis =1; horizontal concatenation
data5.head()

## Q8

In [32]:
data2 = Data.iloc[:,[23,24,25,26]] # all rows of these columns
data2.columns = data2.iloc[0].astype(str) #replacing header with first row
data2 = data2[1:]
data2.head()

0 Microsoft/Windows Apple/MacBook Other  nan
1               NaN             1   NaN  NaN
2               NaN             1   NaN  NaN
3               NaN             1   NaN  NaN
4                 1           NaN   NaN  NaN
5               NaN             2   NaN  NaN

In [33]:
data2 = data2.loc[:,:].replace('1', pd.Series(data2.columns, data2.columns)).fillna('')
data2

0   Microsoft/Windows  Apple/MacBook  Other           nan
1                      Apple/MacBook
2                      Apple/MacBook
3                      Apple/MacBook
4   Microsoft/Windows
5                                  2
6
7   Microsoft/Windows
8
9   Microsoft/Windows
10
11  Microsoft/Windows
12  Microsoft/Windows
13                     Apple/MacBook
14  Microsoft/Windows
15  Microsoft/Windows
16  Microsoft/Windows
17  Microsoft/Windows  Apple/MacBook
18  Microsoft/Windows
19  Microsoft/Windows
20                     Apple/MacBook
21  Microsoft/Windows
22  Microsoft/Windows
23  Microsoft/Windows  Apple/MacBook
24  Microsoft/Windows
25  Microsoft/Windows
26                  0
27                     Apple/MacBook
28  Microsoft/Windows
29  Microsoft/Windows
30                     Apple/MacBook
31  Microsoft/Windows
32  Microsoft/Windows  Apple/MacBook
33  Microsoft/Windows
34  Microsoft/Windows
35  Microsoft/Windows
36                                    Other  Acer/Windows

In [39]:
data3 = data2.loc[:,:].replace('Other', '')
data3 = data3.loc[:,:].replace('2', '')
data3 = data3.loc[:,:].replace('0', ' ')
data3

0   Microsoft/Windows  Apple/MacBook Other           nan
1                      Apple/MacBook
2                      Apple/MacBook
3                      Apple/MacBook
4   Microsoft/Windows
5
6
7   Microsoft/Windows
8
9   Microsoft/Windows
10
11  Microsoft/Windows
12  Microsoft/Windows
13                     Apple/MacBook
14  Microsoft/Windows
15  Microsoft/Windows
16  Microsoft/Windows
17  Microsoft/Windows  Apple/MacBook
18  Microsoft/Windows
19  Microsoft/Windows
20                     Apple/MacBook
21  Microsoft/Windows
22  Microsoft/Windows
23  Microsoft/Windows  Apple/MacBook
24  Microsoft/Windows
25  Microsoft/Windows
26
27                     Apple/MacBook
28  Microsoft/Windows
29  Microsoft/Windows
30                     Apple/MacBook
31  Microsoft/Windows
32  Microsoft/Windows  Apple/MacBook
33  Microsoft/Windows
34  Microsoft/Windows
35  Microsoft/Windows
36                                          Acer/Windows

##Concatenation of Q8 into final column

In [ ]:
data4 = pd.DataFrame(data3.iloc[:,0] + data3.iloc[:,1] + data3.iloc[:,2] + data3.iloc[:,3])
data4.columns = ['Laptop Type']
data5 = pd.concat([data5,data4],axis=1)
data5. head()
#data5 = data5.drop('Laptop Type', axis=1)
#data5.head()

##Q9,Q10....Q13

In [41]:
data2 = Data.iloc[:,27:46]
data2.head()
data2.columns = data2.iloc[0].astype(str) #replacing header with first row
data2 = data2[1:]
data2.head()

,"Yes, Full Time","Working, but not Full Time",Not Working while attending Mason,Little/none,Some familiarity,Average user,Frequent use for projects,Fluent/expert,Little/none,Some familiarity,Average user,Frequent use for projects,Fluent/expert,Little/none,Some familiarity,Average user,Frequent use for projects,Fluent/expert,What is your goal for learning about data analytics?
1,NaN,NaN,1,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN
2,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
3,1,NaN,NaN,NaN,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,"As part of my work, I have access to a lot of ..."
4,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN
5,1,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,Learn

##replacing the 1s with its column names

In [ ]:
data3 = data2.loc[:, :].replace('1', pd.Series(data2.columns, data2.columns)).fillna('')
data3.head()

##Remaining Qs concatenation

In [50]:
Q9= pd.DataFrame(data3.iloc[:,0] + data3.iloc[:,1] + data3.iloc[:,2] )
Q10= pd.DataFrame(data3.iloc[:,3] + data3.iloc[:,4] + data3.iloc[:,5] + data3.iloc[:,6] +data3.iloc[:,7] )
Q11= pd.DataFrame(data3.iloc[:,8] + data3.iloc[:,9] + data3.iloc[:,10] + data3.iloc[:,11]+data3.iloc[:,12] )
Q12= pd.DataFrame(data3.iloc[:,13] + data3.iloc[:,14] + data3.iloc[:,15] + data3.iloc[:,16]+data3.iloc[:,17] )
Q13=pd.DataFrame(data3.iloc[:,18] )
#Q9.head()
#Q10.head()
#Q11.head()
#Q12.head()
#Q13.head()

                  0
1  Some familiarity
2       Little/none
3      Average user
4  Some familiarity
5      Average user

## Setting Columns

In [52]:
Q9.columns = ['Are you employed full-time while attending Mason?']
Q10.columns = ['What is your approximate current level of programming skill in Python?']
Q11.columns = ['What is your approximate current level of programming skill in R?']
Q12.columns = ['What is your approximate current level of programming skill in SQL?']
Q13.columns = ['What is your goal for learning about data analytics?']

##Concatenate all the remaining Qs

In [ ]:
data5 = pd.concat([data5,Q9,Q10,Q11,Q12,Q13],axis=1)
data5.head()

In [55]:
data5.to_csv('580SurveyCleanup_formatted.csv',index=False) #making all changes into cs file back with header by default

#Part 2

In [56]:
formatted_csv = pd.read_csv('580SurveyCleanup_formatted.csv', dtype=object)

In [ ]:
labels = list(formatted_csv.columns)
labels

In [ ]:
null_counter = formatted_csv.isnull().sum() #counting null values
null_counter

## Removing NULL value columns

In [ ]:
formatted_csv = formatted_csv.dropna(axis=1, how='all') #columns which has all NULL values
formatted_csv.head()

## Replacing Missing values

In [73]:

#Replacing with Mode
formatted_csv['Country of Citizenship'] = formatted_csv['Country of Citizenship'].fillna(formatted_csv['Country of Citizenship'].mode()[0])
formatted_csv['Region'] = formatted_csv['Region'].fillna(formatted_csv['Region'].mode()[0])
formatted_csv['City / Town / District'] = formatted_csv['City / Town / District'].fillna(formatted_csv['City / Town / District'].mode()[0])
formatted_csv['Laptop Type'] = formatted_csv['Laptop Type'].fillna(formatted_csv['Laptop Type'].mode()[0])
formatted_csv['Are you employed full-time while attending Mason?'] = formatted_csv['Are you employed full-time while attending Mason?'].fillna(formatted_csv['Are you employed full-time while attending Mason?'].mode()[0])
formatted_csv['What is your approximate current level of programming skill in Python?'] = formatted_csv['What is your approximate current level of programming skill in Python?'].fillna(formatted_csv['What is your approximate current level of programming skill in Python?'].mode()[0])
formatted_csv['What is your approximate current level of programming skill in R?'] = formatted_csv['What is your approximate current level of programming skill in R?'].fillna(formatted_csv['What is your approximate current level of programming skill in R?'].mode()[0])
formatted_csv['What is your approximate current level of programming skill in SQL?'] = formatted_csv['What is your approximate current level of programming skill in SQL?'].fillna(formatted_csv['What is your approximate current level of programming skill in SQL?'].mode()[0])
formatted_csv['Undergraduate Degree'] = formatted_csv['Undergraduate Degree'].fillna(formatted_csv['Undergraduate Degree'].mode()[0])

formatted_csv['Expected Graduation date from Mason MS program?'] = formatted_csv['Expected Graduation date from Mason MS program?'].fillna(formatted_csv['Expected Graduation date from Mason MS program?'].mode()[0])
formatted_csv

,Time,Status,Duration (Seconds),IP Address,Country,Region,City / Town / District,Latitude,Longitude,Which Section,...,Are you employed full-time while attending Mason?,What is your approximate current level of programming skill in Python?,What is your approximate current level of programming skill in R?,What is your approximate current level of programming skill in SQL?,What is your goal for learning about data analytics?,Are you employed full-time while attending Mason?.1,What is your approximate current level of programming skill in Python?.1,What is your approximate current level of programming skill in R?.1,What is your approximate current level of programming skill in SQL?.1,What is your goal for learning about data analytics?.1
0,10/3/20 5:49 PM,Completed,11646,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209,4.0,...,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN,Not Working while attending Mason,Some familiarity,Little/none,Some familiarity,NaN
1,10/3/20 5:49 PM,Completed,113,98.169.26.134,United States,Virginia,Fairfax,-77.263,38.8605,2.0,...,"Working, but not Full Time",Average user,Average user,Little/none,NaN,"Working, but not Full Time",Average user,Average user,Little/none,NaN
2,10/3/20 5:49 PM,Completed,572,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645,2.0,...,"Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ...","Yes, Full Time",Some familiarity,Little/none,Average user,"As part of my work, I have access to a lot of ..."
3,10/3/20 5:50 PM,Completed,365,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175,2.0,...,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN,Not Working while attending Mason,Average user,Frequent use for projects,Some familiarity,NaN
4,10/3/20 5:51 PM,Completed,92,138.88.108.230,United States,Virginia,Fairfax,-97.822,37.751,2.0,...,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn,"Yes, Full Time",Some familiarity,Some familiarity,Average user,Learn
5,10/3/20 5:59 PM,Incomplete,221,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,2.0,...,Not Working while attending Mason,Average user,Average user,Average user,NaN,NaN,NaN,NaN,NaN,NaN
6,10/3/20 6:23 PM,Completed,115983,108.48.175.220,United States,Virginia,Arlington,-77.0987,38.86,2.0,...,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...,"Working, but not Full Time",Average user,Average user,Average user,To deduce meaningful interpretation for Financ...
7,10/3/20 7:10 PM,Incomplete,40,173.67.199.85,United States,Virginia,Ashburn,-77.539,39.018,2.0,...,Not Working while attending Mason,Average user,Average user,Average user,NaN,NaN,NaN,NaN,NaN,NaN
8,10/3/20 7:25 PM,Completed,137,74.96.114.12,United States,Virginia,Woodbridge,-77.3197,38.678,2.0,...,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN,"Yes, Full Time",Some familiarity,Frequent use for projects,Average user,NaN
9,10/3/20 7:56 PM,Incomplete,179,107.77.241.32,United States,Texas,Fairfax,-96.8217,32.7787,4.0,...,Not Working while attending Mason,Average user,Average user,Average user,NaN,NaN,NaN,NaN,NaN,NaN
10,10/3/20 8:14 PM,Completed,127,138.88.182.245,United States,Maryland,Takoma Park,-77.004,38.9827,2.0,...,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...,Not Working while attending Mason,Little/none,Little/none,Some familiarity,To see if it is a field I am interested in pur...
11,10/3/20 9:38 PM,Completed,269,72.83.246.60,United States,Virginia,Fairfax,-77.263,38.8605,4.0,...,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...,Not Working while attending Mason,Frequent use for projects,Average user,Frequent use for projects,To learn and explore cutting edge data technol...
12,10/3/20 9:41 PM,Completed,117,96.241.43.105,United States,Virginia,Chantilly,-77.4512,38.9036,2.0,...,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...,"Working, but not Full Time",Some familiarity,Average user,Average user,Learn to select the appropriate tools to condu...
13,10/3/20 10:49 PM,Completed,5966,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,Not Working while attending Mason,Average user,Average user,Average user,NaN,Not Working while attending Mason,Average user,Average user,Average user,NaN
14,10/3/20 11:25 PM,Completed,254,73.134.53.227,United States,Maryland,Hyattsville,-76.8696,38.9544,4.0,...,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills,Not Working while attending Mason,Average user,Little/none,Little/none,improve my skills
15,10/4/20 12:28 AM,Completed,526,73.86.219.52,United States,Maryland,Baltimore,-76.6355,39.3555,4.0,...,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,My professional goal is to become a Financial ...
16,10/4/20 5:22 AM,Completed,398,69.138.215.127,United States,Virginia,Arlington,-77.113,38.8747,2.0,...,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...,"Yes, Full Time",Average user,Some familiarity,Some familiarity,able to compliment my Computational Social Sci...
17,10/4/20 5:36 AM,Completed,128253,72.196.231.70,United States,Virginia,Springfield,-77.2333,38.7438,2.0,...,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company,Not Working while attending Mason,Frequent use for projects,Frequent use for projects,Average user,To start a company
18,10/4/20 5:47 AM,Completed,239,100.15.54.17,United States,Virginia,Woodbridge,-77.3197,38.678,4.0,...,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...,Not Working while attending Mason,Little/none,Little/none,Average user,To be able understand and manipulate data to m...
19,10/4/20 10:32 AM,Completed,255,184.170.83.239,United States,Virginia,Rustburg,-79.0985,37.2544,4.0,...,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...,"Working, but not Full Time",Some familiarity,Fluent/expert,Average user,My ultimate goal is to get a job as a sports a...
20,10/4/20 11:03 AM,Completed,256,100.36.243.102,United States,Virginia,Fairfax,-77.3375,38.8357,4.0,...,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...,"Yes, Full Time",Some familiarity,Some familiarity,Some familiarity,To understand how to properly interpret and di...
21,10/4/20 12:34 PM,Completed,674,108.56.134.80,United States,Virginia,Reston,-77.3489,38.9311,2.0,...,Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself...",Not Working while attending Mason,Some familiarity,Little/none,Average user,"After graduating data analytics, I want myself..."
22,10/4/20 1:36 PM,Completed,130,73.163.163.82,United States,Maryland,Baltimore,-76.557,39.2784,4.0,...,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...,"Working, but not Full Time",Some familiarity,Frequent use for projects,Little/none,Learning how to appropriately handle large qua...
23,10/4/20 1:50 PM,Completed,275,138.88.223.87,United States,Virginia,Fairfax,-97.822,37.751,4.0,...,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...,Not Working while attending Mason,Little/none,Little/none,Little/none,To learn and understand the fundamentals and m...
24,10/4/20 9:28 PM,Completed,325,100.36.50.114,United States,Virginia,Fairfax,-97.822,37.751,4.0,...,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...,"Yes, Full Time",Average user,Average user,Average user,The goal is to learn as many programming/stati...
25,10/5/20 9:37 AM,Completed,257,108.51.59.195,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learning analytics tool and being good at them
26,10/5/20 9:36 AM,Completed,657,72.83.246.219,United States,Virginia,Fairfax,-77.263,38.8605,2.0,...,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst,Not Working while attending Mason,Average user,Frequent use for projects,Average user,I want to be as a data analyst
27,10/5/20 10:36 AM,Completed,1750,100.36.118.186,United States,Virginia,Burke,-77.2866,38.7851,4.0,...,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...,Not Working while attending Mason,Average user,Frequent use for projects,Average user,It is very relevant to my PhD research area an...
28,10/5/20 11:02 AM,Completed,887,172.58.187.98,United States,Maryland,Baltimore,-76.6949,39.282,4.0,...,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...,Not Working while attending Mason,Average user,Average user,Average user,Learn how to handle large amount structured an...
29,10/5/20 11:17 AM,Completed,180,72.196.230.201,United States,Virginia,Springfield,-77.2333,38.7438,2.0,...,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...,Not Working while attending Mason,Average user,Average user,Frequent use for projects,To become a good Data Analyst and work for top...
30,10/5/20 12:52 PM,Completed,392,108.18.111.204,United States,Virginia,Lorton,-77.206,38.6911,4.0,...,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...,"Yes, Full Time",Little/none,Some familiarity,Some familiarity,Get a better understanding of the granularity ...
31,10/5/20 12:56 PM,Incomplete,192,71.191.72.223,United States,Virginia,Burke,-77.2866,38.7851,2.0,...,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN,Not Working while attending Mason,Average user,Frequent use for projects,Frequent use for projects,NaN
32,10/5/20 1:52 PM,Completed,277,184.191.72.8,United States,Virginia,Falls Church,-77.1425,38.8472,2.0,...,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works,"Yes, Full Time",Average user,Some familiarity,Some familiarity,Learn how data analytics works
33,10/5/20 3:34 PM,Completed,119,141.156.160.243,United States,Virginia,Fairfax,-97.822,37.751,4.0,...,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science,"Yes, Full Time",Average user,Average user,Average user,Advance my career in data science
34,10/5/20 3:41 PM,Completed,149,71.206.51.121,United States,Maryland,Frederick,-77.2758,39.4624,2.0,...,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job,Not Working while attending Mason,Some familiarity,Some familiarity,Some familiarity,Getting a good job
35,10/5/20 5:58 PM,Completed,285,129.174.252.234,United States,Virginia,Fairfax,-77.3375,38.8357,4.0,...,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.,"Yes, Full Time",Some familiarity,Little/none,Little/none,to use the skills at work.

##Why choose MODE for replacement?

Mode is particularly useful when dealing with categorical or nominal data, where the data points are divided into clear/different categories or classes.Filling missing values with the mode can help preserve the distribution of the categorical variable and using the mode is a straightforward and simple approach.

In [ ]:
formatted_csv = formatted_csv.replace('6l',61) #error in writing 61 as 6l
formatted_csv = formatted_csv.replace('7O',70)
formatted_csv

In [ ]:
formatted_csv['Height (Inches)'] = pd.to_numeric(formatted_csv['Height (Inches)'])
formatted_csv['Height (Inches)'] = formatted_csv['Height (Inches)'].fillna(formatted_csv['Height (Inches)'].mean())
formatted_csv
#column1_values = formatted_csv['Height (Inches)']
#print(column1_values)

## Why using MEAN here?

- float type is continous form of data so mean here will provide a reasonable estimate.
- It can reduce bias in your dataset, particularly when the missing values are missing at random or the distribution is relatively symmetrical.
- In continuous data, using the mode (which is a single value) may not be suitable because there might not be a clear mode, or the mode may not adequately represent the central tendency of the data.

In [80]:
formatted_csv['What is your goal for learning about data analytics?'] = formatted_csv['What is your goal for learning about data analytics?'].fillna('To upskill and get a job')

Replacing missing/empty values for goal with a common answer using the number of answers we have got

In [ ]:
formatted_csv['Age (years)'] = formatted_csv['Age (years)'].replace('2 3',23)
formatted_csv['Age (years)'] = formatted_csv['Age (years)'].replace('1993',30)
formatted_csv

In [ ]:
formatted_csv['Country of Citizenship'] = formatted_csv['Country of Citizenship'].replace('USA','United States')
formatted_csv['Country of Citizenship'] = formatted_csv['Country of Citizenship'].replace('US','United States')
formatted_csv['Undergraduate Degree'] = formatted_csv['Undergraduate Degree'].replace('Yes',' ') #replaced yes with empty string
#formatted_csv #maintaining a standard
column1_values = formatted_csv['Undergraduate Degree']
print(column1_values)

In [89]:
formatted_csv.to_csv('580SurveyCleanup_cleaned.csv',index=False)

#Part 3

In [95]:

cleaned_csv = pd.read_csv('580SurveyCleanup_cleaned.csv')

# Define the list of question labels and the labels for 'Height (Inches)' and 'Age (years)'
question_labels = [
    'Which Section', 'Gender', 'Age (years)', 'Height (Inches)', 'Country of Citizenship', 'Undergraduate Degree',
    'Expected Graduation date from Mason MS program?', 'Laptop Type', 'Are you employed full-time while attending Mason?',
    'What is your approximate current level of programming skill in Python?', 'What is your approximate current level of programming skill in R?',
    'What is your approximate current level of programming skill in SQL?', 'What is your goal for learning about data analytics?'
]
height_label = 'Height (Inches)'
age_label = 'Age (years)'

# Initialize dictionaries to store medians and top values
medians = {}
top = {}

# Calculate medians and top values for specific columns
medians[height_label] = cleaned_csv[height_label].astype(float).median()
medians[age_label] = cleaned_csv[age_label].astype(float).median()

top[height_label] = cleaned_csv[height_label].astype(float).max()
top[age_label] = cleaned_csv[age_label].astype(float).max()

# Initialize a DataFrame to store descriptions
descriptions = pd.DataFrame()

# Calculate and append descriptions for each column
for label in question_labels:
    desc = cleaned_csv[label].describe().to_frame().T
    descriptions = descriptions.append(desc)

# Append medians and top values to the DataFrame
descriptions = descriptions.append(pd.Series(medians, name='Median'))
descriptions = descriptions.append(pd.Series(top, name='Max'))

# Reset the index for the DataFrame
descriptions.reset_index(drop=True, inplace=True)

# Print or use the 'descriptions' DataFrame as needed
print(descriptions)

   count       mean        std   min    25%   50%   75%   max unique  \
0   36.0   2.888889   1.007905   2.0   2.00   2.0   4.0   4.0    NaN
1     36        NaN        NaN   NaN    NaN   NaN   NaN   NaN      4
2   36.0  27.138889   6.503418  22.0  23.00  25.0  28.0  55.0    NaN
3   36.0  65.720000  11.167422   5.2  65.93  67.0  70.0  75.0    NaN
4     36        NaN        NaN   NaN    NaN   NaN   NaN   NaN     17
5     36        NaN        NaN   NaN    NaN   NaN   NaN   NaN     31
6     36        NaN        NaN   NaN    NaN   NaN   NaN   NaN     24
7     36        NaN        NaN   NaN    NaN   NaN   NaN   NaN      5
8     36        NaN        NaN   NaN    NaN   NaN   NaN   NaN      3
9     36        NaN        NaN   NaN    NaN   NaN   NaN   NaN      4
10    36        NaN        NaN   NaN    NaN   NaN   NaN   NaN      5
11    36        NaN        NaN   NaN    NaN   NaN   NaN   NaN      4
12    36        NaN        NaN   NaN    NaN   NaN   NaN   NaN     28
13   NaN        NaN        NaN   NaN    NaN   NaN   NaN   NaN    NaN
14   NaN        NaN        NaN   NaN    NaN   NaN   NaN   NaN    NaN

                                  top freq  Height (Inches)  Age (years)
0                                 NaN  NaN              NaN          NaN
1                                Male   18              NaN          NaN
2                                 NaN  NaN              NaN          NaN
3                                 NaN  NaN              NaN          NaN
4                               India   11              NaN          NaN
5                           Economics    5              NaN          NaN
6                          2021-12-20    6              NaN          NaN
7                   Microsoft/Windows   24              NaN          NaN
8   Not Working while attending Mason   20              NaN          NaN
9                        Average user   18              NaN          NaN
10                       Average user   12              NaN          NaN
11                       Average user   18              NaN          NaN
12           To upskill and get a job    9              NaN          NaN
13                                NaN  NaN             67.0         25.0
14                                NaN  NaN             75.0         55.0

<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:31: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(desc)
<ipython-input-95-8cffb92760b3>:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(pd.Series(medians, name='Median'))
<ipython-input-95-8cffb92760b3>:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  descriptions = descriptions.append(pd.Series(top, name='Max'))

In [96]:
cleaned_csv.to_csv('580SurveyFinal.csv',index=False)